### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by olaferlandsen** [souzadriano/ionic2-google-places-autocomplete#4]
Hi Adriano,
This "work" but with this error:
```
Failed to load https://maps.googleapis.com/maps/api/place/autocomplete/json?input=gooogle&key=xxx: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access.
``` 
Have you idea if it still work?

**Comment by souzadriano** [comment]
Hi @olaferlandsen,

This is a CORS problem in development.

In development I use the chrome extension [Allow-Control-Allow-Origin: *](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi) and configure maps.googleapis.com in the URL patterns.

**Comment by olaferlandsen** [comment]
I know it, but why you don't use jsonp???

**Comment by souzadriano** [comment]
Thanks @olaferlandsen,  I will search and try change to jsonp if better.

**Comment by acittar** [comment]
Hi Adriano,

I installed the chrome extension but I get the same error. How did you configured it?

Thanks,
Alessandro

**Comment by souzadriano** [comment]
Hi @acittar,

Try this:
![image](https://user-images.githubusercontent.com/6888325/35675843-ae5455f4-0730-11e8-9ca4-c8b14cf73a02.png)

**Comment by ishan123456789** [comment]
Not able to solve it using the plugin.Please suggest a fix or way through.
![screen shot 2018-02-21 at 11 06 21 am](https://user-images.githubusercontent.com/23247168/36464716-62da813a-16f7-11e8-8ec4-4a09c0656bc6.png)

**Comment by souzadriano** [comment]
Hi @ishan123456789 

With below configs works for me:
![image](https://user-images.githubusercontent.com/6888325/36489344-99b26a44-1704-11e8-9062-2f237cbef574.png)

What Ionic version you use?

**Comment by ishan123456789** [comment]
`cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-sim : 6.1.2
    Node    : v8.9.4
    npm     : 5.6.0
    OS      : OS X Yosemite
    Xcode   : Xcode 7.2 Build version 7C68

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro`

**Comment by ishan123456789** [comment]
I solved the issue by adding another extension ie. 

https://chrome.google.com/webstore/detail/cors-goggle/jioikioepegflmdnbocfhgmpmopmjkim/related?hl=en

The one you referred did not help

**Comment by acittar** [comment]
Guys,

with the chrome extension Allow-Control-Allow-Origin: * configured as Adriano said, I just have to disable and re-enable it when I open my app in a new tab

![image](https://user-images.githubusercontent.com/25658805/36540270-0724ff26-17da-11e8-9f61-62c0c61b3e94.png)

Thanks,
Alessandro

**Comment by acittar** [comment]
Hi Adriano,

sorry, I still have this problem in my production environment. Do you have any idea about how can I fix it?

Thanks,
Alessandro

**Comment by ishan123456789** [comment]
This shouldn't be an issue on mobile app. As CORS issue is not relevant to mobile apps

**Comment by acittar** [comment]
Sure, but what if a user accesses my app via browser?

**Comment by acittar** [comment]
Hi Adriano,

do you have any news on this? The plugin works perfectly for Android/iOS app (I didn't try but I think so), but it doesn't work at all for PWA. I deployed my PWA on heroku and it doesn't work if my chrome plugin is disabled.

Thanks a lot,
Alessandro

**Comment by souzadriano** [comment]
Hi @acittar ,

I don't use as PWA.

I think that is a server configuration.

How is your server configured?

You can try this:
https://devdactic.com/deploy-ionic-website-heroku/
with CORS configurations.

**Comment by acittar** [comment]
Hi Adriano,

Tried a lot of configurations to allow CORS but without success. Are you going to switch to jsonp in the next future? It should solve the issue even in local env.

Thanks,
Alessandro

**Comment by neharuparel** [comment]
I am still getting the CORS issue in production mode also in my ionic application.
Has anyone solved the issue and how please let me know.
